export const LOAD_MAPPINGS_SUCCESS = 'LOAD_MAPPINGS_SUCCESS';
export const LOAD_RESOURCE_SUCCESS = 'LOAD_RESOURCE_SUCCESS';
export const LOAD_RESOURCES_SUCCESS = 'LOAD_RESOURCES_SUCCESS';

export const POST_MAPPING_SUCCESS= 'POST_MAPPING_SUCCESS';
export const ADD_RESOURCE = 'ADD_RESOURCE';
export const ADD_MAPPING = 'ADD_MAPPING';
export const SAVE_MAPPING = 'SAVE_MAPPING';
export const DELETE_MAPPING_SUCCESS = 'DELETE_MAPPING_SUCCESS';
export const UPDATE_MAPPING_SUCCESS = 'UPDATE_MAPPING_SUCCESS';



export const POST_RESOURCE_SUCCESS = 'POST_RESOURCE_SUCCESS';
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';
export const UPDATE_RESOURCE_SUCCESS = 'UPDATE_RESOURCE_SUCCESS';



export const ADD_ELEMENTS_TO_GRAPH = 'ADD_ELEMENT_TO_GRAPH';
export const SET_GRAPH_LAYOUT = 'SET_GRAPH_LAYOUT';

export const SET_INFO_MESSAGE = 'SET_INFO_MESSAGE';
export const SET_FORM_TYPE = 'SET_FORM_TYPE';
export const SET_BOTTOM_PANEL_VIEW = 'SET_BOTTOM_PANEL_VIEW';
export const SET_EDIT_DETAIL = 'SET_EDIT_DETAIL';
export const CANCEL_EDIT = 'CANCEL_EDIT';



export const TOGGLE_COLLAPSE_MENU = 'TOGGLE_COLLAPSE_MENU';