export const LOAD_MAPPINGS_SUCCESS = 'LOAD_MAPPINGS_SUCCESS';
export const LOAD_RESOURCE_SUCCESS = 'LOAD_RESOURCE_SUCCESS';
export const LOAD_RESOURCES_SUCCESS = 'LOAD_RESOURCES_SUCCESS';
export const LOAD_DEPENDENCIES_SUCCESS = 'LOAD_DEPENDENCIES_SUCCESS';
export const LOAD_ACTIVE_MAPPING_SUCCESS = 'LOAD_ACTIVE_MAPPING_SUCCESS';
export const LOAD_ACTIVE_MAPPING_RESOURCES = 'LOAD_ACTIVE_MAPPING_RESOURCES';
export const CLEAR_ACTIVE_MAPPING_SELECTION = 'CLEAR_ACTIVE_MAPPING_SELECTION'
export const SET_ACTIVE_MAPPING_CONNECTIONS = 'SET_ACTIVE_MAPPING_CONNECTIONS';
export const ADD_ACTIVE_MAPPING_CONNECTIONS = 'ADD_ACTIVE_MAPPING_CONNECTIONS';
export const ADD_ACTIVE_MAPPING_RESOURCES = 'ADD_ACTIVE_MAPPING_RESOURCES';
export const ADD_ACTIVE_MAPPING_RESOURCE = 'ADD_ACTIVE_MAPPING_RESOURCE';
export const POST_MAPPING_SUCCESS= 'POST_MAPPING_SUCCESS';
export const LOAD_CATEGORIES_SUCCESS= 'LOAD_CATEGORIES_SUCCESS';
export const SAVE_ACTIVE_MAPPING_CHANGES_LOCALLY= 'SAVE_ACTIVE_MAPPING_CHANGES_LOCALLY';
export const ADD_RESOURCE = 'ADD_RESOURCE';
export const ADD_MAPPING = 'ADD_MAPPING';
export const SAVE_MAPPING = 'SAVE_MAPPING';
export const ADD_TAG = 'ADD_TAG';
export const ADD_TAG_SUCCESS = 'POST_TAG_SUCCESS';
export const REMOVE_ACTIVE_MAPPING_RESOURCE = 'REMOVE_ACTIVE_MAPPING_RESOURCE';
export const DELETE_MAPPING_SUCCESS = 'DELETE_MAPPING_SUCCESS';
export const UPDATE_MAPPING_SUCCESS = 'UPDATE_MAPPING_SUCCESS';



export const POST_RESOURCE_SUCCESS = 'POST_RESOURCE_SUCCESS';
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';
export const UPDATE_RESOURCE_SUCCESS = 'UPDATE_RESOURCE_SUCCESS';

export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';

export const SET_ACTIVE_DETAIL = 'SET_ACTIVE_DETAIL';
export const CLEAR_ACTIVE_DETAIL = 'CLEAR_ACTIVE_DETAIL';

export const INIT_GRAPH = 'INIT_GRAPH';
export const ADD_ELEMENTS_TO_GRAPH = 'ADD_ELEMENT_TO_GRAPH';
export const REMOVE_ELEMENT_FROM_GRAPH = 'REMOVE_ELEMENT_FROM_GRAPH';

export const SET_FORM_TYPE = 'SET_FORM_TYPE';
export const SET_BOTTOM_PANEL_VIEW = 'SET_BOTTOM_PANEL_VIEW';
export const SET_EDIT_DETAIL = 'SET_EDIT_DETAIL';
export const CANCEL_EDIT = 'CANCEL_EDIT';