FROM alpine
FROM node:latest
WORKDIR /usr/webapp/src
RUN mkdir build
COPY package.json .
COPY src src/.
COPY public public/.
RUN npm install

# mount path to ./build in
# docker-compose.dist.yml

CMD ["npm", "run", "build"]
