# Generated by Django 2.0.3 on 2018-07-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyMap',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('connected_to', models.ManyToManyField(blank=True, to='application.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, to='application.Tag'),
        ),
        migrations.AddField(
            model_name='dependencymap',
            name='resources',
            field=models.ManyToManyField(blank=True, to='application.Resource'),
        ),
        migrations.AddField(
            model_name='dependencymap',
            name='tags',
            field=models.ManyToManyField(blank=True, to='application.Tag'),
        ),
    ]
