# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('connected_to', models.ManyToManyField(to='application.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='SemanticCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='dependencymap',
            name='resources',
            field=models.ManyToManyField(to='application.Resource'),
        ),
    ]
