# Generated by Django 2.0.3 on 2018-10-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('connected_to', models.ManyToManyField(blank=True, to='application.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DependencyMap',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('resources', models.ManyToManyField(related_name='resources', to='application.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='dependencymap',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='application.Tag'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='application.Tag'),
        ),
    ]
