# Generated by Django 2.0.3 on 2018-04-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='connected_to',
            field=models.ManyToManyField(null=True, to='application.Resource'),
        ),
    ]
