# Generated by Django 2.0.3 on 2018-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencymap',
            name='resources',
            field=models.ManyToManyField(to='application.Resource'),
        ),
        migrations.AlterField(
            model_name='dependencymap',
            name='tags',
            field=models.ManyToManyField(to='application.Tag'),
        ),
    ]
