# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180430_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencymap',
            name='description',
            field=models.TextField(),
        ),
    ]
