# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-30 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20180430_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='categories',
            field=models.ManyToManyField(blank=True, to='application.SemanticCategory'),
        ),
        migrations.AlterField(
            model_name='dependencymap',
            name='resources',
            field=models.ManyToManyField(blank=True, to='application.Resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='connected_to',
            field=models.ManyToManyField(blank=True, to='application.Resource'),
        ),
    ]
