# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-02 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20180430_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='semanticcategory',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
