# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-02 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20180502_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='info',
            new_name='description',
        ),
    ]
